services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=analyzer
      - POSTGRES_DB=gymbook_analyzer
